package com.example.MerchantProject.enums;

public enum BrandCategories {
    FASHION_AND_ACCESSORIES, TRAVEL_LEISURE_AND_DAYS_OUT, DINING_OUT, DEPARTMENT_STORE, ELECTRONIC, GAMING_AND_CONTENT,
    HOBBIES, PETS, HOME_AND_GARDEN, LUXURY_AND_JEWELLERY, SPORTS_AND_FITNESS, CHILDREN_AND_TOYS
}
